name: install-opendylan
description: Install the Open Dylan compiler
inputs:
  version:
    required: false
    type: string
    default: 2022.1
  tag:
    required: false
    type: string
    default: v2022.1.0

runs:
  using: composite
  steps:
    - name: Install Open Dylan
      env:
        OD_VERSION: ${{ inputs.version }}
        OD_TAG: ${{ inputs.tag }}
      shell: bash
      run: |
        echo "Installing Open Dylan..."
        env | sort  # debug
        os=linux
        if [[ "$(uname -s)" == "Darwin" ]]; then
          os=darwin
        fi
        # We don't want to pollute the checkout directory so extract OD into
        # its parent. ${GITHUB_WORKSPACE} is of the form .../repo-name/repo-name.
        cd ${GITHUB_WORKSPACE}/..
        curl -L -o opendylan.tar.bz2 https://github.com/dylan-lang/opendylan/releases/download/${OD_TAG}/opendylan-${OD_VERSION}-x86_64-${os}.tar.bz2
        tar xfj opendylan.tar.bz2
        ln -s opendylan-${OD_VERSION} opendylan
        ln -s opendylan-${OD_VERSION}/bin/dylan-compiler
        ln -s opendylan-${OD_VERSION}/bin/dylan
        echo "Compiler: ${PWD}/dylan-compiler"
        echo "dylan-tool: ${PWD}/dylan"
        echo -n "Open Dylan "
        ./dylan-compiler -version
        echo -n "dylan-tool version: "
        ./dylan version
